import React from 'react';
import {
  Activity,
  Cpu,
  Fish,
  Radio,
  FileText,
  Smartphone,
  Database,
  Bell,
  Users,
  Globe,
  MapPin,
  Mail,
  Phone,
  Building2,
  CheckCircle,
  TrendingUp,
  Shield,
  Droplets,
  Award,
  Target,
} from 'lucide-react';

/* ─── Design tokens ──────────────────────────────────────────────── */
const T = '#0F6E56';      // deep teal primary
const HERO = '#083d2e';   // dark teal hero

/* ─── Reusable primitives ────────────────────────────────────────── */
const SectionLabel = ({ children }) => (
  <p style={{ color: T, letterSpacing: '0.12em' }}
    className="text-[11px] font-bold uppercase mb-2">
    {children}
  </p>
);

const SectionHeading = ({ children }) => (
  <h2 className="text-2xl md:text-3xl font-extrabold text-gray-900 font-outfit mb-0 leading-snug">
    {children}
  </h2>
);

const Divider = () => (
  <div style={{ backgroundColor: T }} className="w-12 h-1 mt-4 mb-8" />
);

export default function About() {
  /* ── Data ── */
  const stats = [
    { number: '400M+',   label: 'People dependent on the Ganga basin' },
    { number: '2,525 km', label: 'Total length of the Ganga river' },
    { number: '12,000+', label: 'Industries polluting the basin' },
    { number: '2.6B L',  label: 'Untreated sewage discharged daily' },
  ];

  const visionBadges = [
    'Zero undetected industrial discharge',
    'AI-driven CPCB enforcement',
    'Gangetic Dolphin recovery',
    '400M+ lives protected',
  ];

  const services = [
    {
      Icon: Activity,
      title: 'Real-time pollution prediction',
      desc: '5-day forecasts for BOD, Dissolved Oxygen, pH, turbidity, and heavy metal levels — generated by LSTM neural networks trained on CPCB sensor data. Alerts triggered 6–12 hours before threshold breach.',
    },
    {
      Icon: Cpu,
      title: 'AI root cause engine',
      desc: 'Identifies the exact factory, chemical type, and discharge time responsible for a pollution spike — with 80%+ accuracy, within 2 hours. Replaces a process that previously took 3–5 days manually.',
    },
    {
      Icon: Database,
      title: 'Digital twin simulation',
      desc: 'A virtual model of the Ganga river simulates how pollution spreads and how interventions (tannery shutdown, STP activation) will impact water quality — before real action is taken.',
    },
    {
      Icon: Fish,
      title: 'Biodiversity risk monitoring',
      desc: 'Real-time habitat health tracking for the Gangetic River Dolphin, Hilsa Fish, and Gharial — India\'s 3 key river indicator species. Automated breeding season alerts and nesting zone protection.',
    },
    {
      Icon: FileText,
      title: 'Industry compliance portal',
      desc: 'AI-powered compliance monitoring for industrial units. Automated ESG and CSR reporting. Tannery and factory discharge benchmarking against CPCB permissible limits.',
    },
    {
      Icon: Smartphone,
      title: 'Citizen mobile app',
      desc: 'River health scores for local ghats and water bodies. Pollution reporting by citizens, processed and routed to authorities. 10,000+ reports per month integrated into the main AI dashboard.',
    },
  ];

  const responsibilities = [
    {
      Icon: Radio,
      title: 'Continuous data acquisition',
      desc: 'Operating and maintaining IoT sensor networks across 52 telemetry nodes. Integrating CPCB sensor feeds, ISRO Bhuvan satellite imagery, Sentinel Hub data, and real-time weather APIs for comprehensive basin coverage.',
    },
    {
      Icon: Cpu,
      title: 'AI model development & maintenance',
      desc: 'Training, validating, and improving LSTM and Random Forest models. Ensuring 80%+ root cause accuracy across diverse pollution scenarios including industrial effluent, municipal sewage, and agricultural runoff.',
    },
    {
      Icon: FileText,
      title: 'Government reporting & enforcement support',
      desc: 'Generating automated compliance reports for CPCB, NMCG, and State Pollution Control Boards. Providing empirical, court-admissible pollution data to support environmental litigation and regulatory enforcement.',
    },
    {
      Icon: Bell,
      title: 'Early warning & crisis response',
      desc: 'Issuing automated alerts to Sewage Treatment Plants (STPs), district administrations, and NMCG when pollution forecasts exceed safe thresholds — minimising fish kills and drinking water contamination events.',
    },
    {
      Icon: Users,
      title: 'Public transparency & citizen engagement',
      desc: 'Maintaining publicly accessible river health dashboards and mobile applications. Processing citizen pollution reports and converting them into actionable intelligence for field enforcement teams.',
    },
  ];

  const achievements = [
    {
      title: "India's first river AI forecast",
      desc: "First system to generate 5-day BOD and DO forecasts for any Indian river using LSTM neural networks — a capability no existing CPCB or NMCG system offers.",
    },
    {
      title: '2-hour source attribution',
      desc: 'Reduced factory-level pollution source identification from 3–5 days (manual lab sampling) to under 2 hours using AI-powered chemical signature analysis.',
    },
    {
      title: 'Digital Twin of the Ganga',
      desc: 'First virtual simulation model of the Ganga river — enabling policymakers to test intervention outcomes (tannery closures, STP upgrades) before committing resources.',
    },
    {
      title: '3 endangered species on one platform',
      desc: "First integrated platform in India combining water quality monitoring with real-time habitat risk assessment for the Gangetic Dolphin, Gharial, and Hilsa Fish.",
    },
    {
      title: 'Kanpur–Varanasi pilot deployed',
      desc: 'Active pilot covering 620 km of the most critically polluted industrial stretch of the Ganga, with 52 IoT telemetry nodes and 40+ million people in the monitored zone.',
    },
    {
      title: 'Multi-stakeholder dashboard',
      desc: 'Unified platform serving government agencies, industries, NGOs, citizens, and universities — consolidating data that was previously siloed across multiple departments.',
    },
  ];

  const contacts = [
    {
      Icon: Building2,
      label: 'Headquarters',
      lines: [
        'NMCG Office, 1st Floor,',
        'Major Dhyanchand National Stadium,',
        'India Gate, New Delhi — 110002',
      ],
    },
    {
      Icon: Mail,
      label: 'Email',
      lines: [
        'contact@example.in',
        'support@example.in',
        '(placeholder — replace before launch)',
      ],
    },
    {
      Icon: Phone,
      label: 'Helpline',
      lines: [
        '1800-XXX-XXXX (Toll Free)',
        'Mon–Sat, 9 AM – 6 PM IST',
        '(placeholder number)',
      ],
    },
    {
      Icon: Globe,
      label: 'Portal',
      lines: [
        'www.example.in',
        'API access: api.example.in',
        '(placeholder — do not link until confirmed)',
      ],
    },
  ];

  /* ── Render ── */
  return (
    <div className="bg-white min-h-screen font-sans text-left">

      {/* ══════════════════════════════════════════════
          S1 — HERO BANNER
      ══════════════════════════════════════════════ */}
      <section style={{ backgroundColor: HERO }} className="w-full py-20 px-4">
        <div className="max-w-5xl mx-auto">
          <p style={{ color: '#86c9b4', letterSpacing: '0.14em' }}
            className="text-[11px] font-bold uppercase mb-4">
            About Us
          </p>
          <h1 className="text-3xl md:text-5xl font-black text-white font-outfit uppercase leading-tight mb-4">
            Ganga Guardian <span style={{ color: '#f5a623' }}>AI</span>
          </h1>
          <p style={{ color: '#86c9b4' }} className="text-lg md:text-xl font-semibold tracking-wide mb-6">
            Predict. Prevent. Protect India's Rivers.
          </p>
          <p className="text-white/70 text-sm md:text-base leading-relaxed max-w-2xl mb-10">
            A national river intelligence initiative developed under the Ministry of Jal Shakti and the
            National Mission for Clean Ganga — India's first AI-powered proactive pollution monitoring system.
          </p>
          {/* Meta pills */}
          <div className="flex flex-wrap gap-3">
            {[
              'Established: 2026',
              'Headquarters: New Delhi, India',
              'Sector: Environmental Tech / GovTech',
            ].map((pill) => (
              <span
                key={pill}
                style={{ borderColor: '#86c9b4', color: '#86c9b4' }}
                className="border px-4 py-1.5 text-[11px] font-bold uppercase tracking-wider"
              >
                {pill}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S2 — ORGANIZATION
      ══════════════════════════════════════════════ */}
      <section className="py-20 px-4 border-b border-gray-100">
        <div className="max-w-5xl mx-auto">
          <SectionLabel>Organization</SectionLabel>
          <SectionHeading>Who we are</SectionHeading>
          <Divider />

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 mb-14">
            <p className="text-gray-600 text-sm md:text-base leading-relaxed">
              Ganga Guardian AI is a government-aligned technology initiative established in 2024, operating
              under the National Mission for Clean Ganga (NMCG) and the Ministry of Jal Shakti. The platform
              was born out of a critical need — despite ₹40,000 crore spent under Namami Gange, the river
              continues to be polluted because existing systems only react after damage has occurred.
            </p>
            <p className="text-gray-600 text-sm md:text-base leading-relaxed">
              The Ganga river basin supports over 400 million people across 11 states, covering 26% of India's
              landmass. It is home to critically endangered species including the Gangetic River Dolphin,
              Gharial, and the Hilsa Fish. Ganga Guardian AI was built to protect this irreplaceable ecosystem
              through artificial intelligence and real-time data.
            </p>
          </div>

          {/* Stat cards */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {stats.map((s) => (
              <div
                key={s.label}
                style={{ borderTopColor: T }}
                className="bg-gray-50 border border-gray-200 border-t-4 p-6"
              >
                <div style={{ color: T }} className="text-2xl md:text-3xl font-black font-outfit mb-2">
                  {s.number}
                </div>
                <p className="text-gray-500 text-xs leading-snug font-medium uppercase tracking-wide">
                  {s.label}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S3 — MISSION
      ══════════════════════════════════════════════ */}
      <section className="py-20 px-4 border-b border-gray-100 bg-gray-50/50">
        <div className="max-w-5xl mx-auto">
          <SectionLabel>Mission</SectionLabel>
          <SectionHeading>Our mission</SectionHeading>
          <Divider />

          <blockquote
            style={{ borderLeftColor: T }}
            className="border-l-4 pl-6 mb-8"
          >
            <p className="text-gray-800 text-base md:text-lg font-medium leading-relaxed italic">
              "To transform India's river monitoring from a reactive, delayed system into a proactive,
              predictive intelligence network — detecting pollution before it spreads, identifying its
              source within hours, and empowering authorities to act before irreversible environmental
              damage occurs."
            </p>
          </blockquote>
          <p className="text-gray-600 text-sm md:text-base leading-relaxed max-w-3xl">
            We exist to bridge the fundamental gap in India's environmental governance: ₹40,000 crore has
            been spent reactively. Ganga Guardian AI acts proactively — shifting the paradigm from
            <strong className="text-gray-800"> 'detect and report' </strong>
            to
            <strong className="text-gray-800"> 'predict and prevent.'</strong>
          </p>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S4 — VISION
      ══════════════════════════════════════════════ */}
      <section className="py-20 px-4 border-b border-gray-100">
        <div className="max-w-5xl mx-auto">
          <SectionLabel>Vision</SectionLabel>
          <SectionHeading>Our vision</SectionHeading>
          <Divider />

          <div className="space-y-5 mb-10 max-w-3xl">
            <p className="text-gray-600 text-sm md:text-base leading-relaxed">
              A future where every major Indian river — Ganga, Yamuna, Narmada, Godavari — is monitored
              by an intelligent, always-on AI network. A future where no industrial unit can discharge
              toxic effluents undetected, where Gangetic Dolphins swim in unpolluted waters, and where
              the 400 million people dependent on the Ganga basin have access to clean water data in
              real time.
            </p>
            <p className="text-gray-600 text-sm md:text-base leading-relaxed">
              By 2027, Ganga Guardian AI aims to become India's national river intelligence backbone —
              covering all 296 CPCB-identified polluted river stretches across the country.
            </p>
          </div>

          {/* Vision badge pills */}
          <div className="flex flex-wrap gap-3">
            {visionBadges.map((badge) => (
              <span
                key={badge}
                style={{ backgroundColor: `${T}12`, color: T, borderColor: `${T}40` }}
                className="border px-4 py-1.5 text-[11px] font-bold uppercase tracking-wider"
              >
                {badge}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S5 — SERVICES
      ══════════════════════════════════════════════ */}
      <section className="py-20 px-4 border-b border-gray-100 bg-gray-50/50">
        <div className="max-w-5xl mx-auto">
          <SectionLabel>Services</SectionLabel>
          <SectionHeading>What we provide</SectionHeading>
          <Divider />

          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            {services.map(({ Icon, title, desc }) => (
              <div
                key={title}
                className="bg-white border border-gray-200 p-6 flex gap-5 items-start"
              >
                <div
                  style={{ backgroundColor: `${T}12`, color: T }}
                  className="p-3 shrink-0"
                >
                  <Icon className="h-5 w-5" />
                </div>
                <div>
                  <h3 className="font-bold text-gray-900 text-sm uppercase tracking-wide mb-2 font-outfit">
                    {title}
                  </h3>
                  <p className="text-gray-500 text-xs leading-relaxed">{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S6 — ROLES & RESPONSIBILITIES
      ══════════════════════════════════════════════ */}
      <section className="py-20 px-4 border-b border-gray-100">
        <div className="max-w-5xl mx-auto">
          <SectionLabel>Roles &amp; responsibilities</SectionLabel>
          <SectionHeading>Our responsibilities</SectionHeading>
          <Divider />

          <div className="space-y-6">
            {responsibilities.map(({ Icon, title, desc }) => (
              <div key={title} className="flex gap-5 items-start border-b border-gray-100 pb-6 last:border-b-0 last:pb-0">
                <div
                  style={{ backgroundColor: T, color: '#fff' }}
                  className="p-2.5 rounded-full shrink-0 mt-0.5"
                >
                  <Icon className="h-4 w-4" />
                </div>
                <div>
                  <h3 className="font-bold text-gray-900 text-sm uppercase tracking-wide mb-1.5 font-outfit">
                    {title}
                  </h3>
                  <p className="text-gray-500 text-xs md:text-sm leading-relaxed">{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S7 — ACHIEVEMENTS
      ══════════════════════════════════════════════ */}
      <section className="py-20 px-4 border-b border-gray-100 bg-gray-50/50">
        <div className="max-w-5xl mx-auto">
          <SectionLabel>Achievements</SectionLabel>
          <SectionHeading>Key milestones</SectionHeading>
          <Divider />

          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            {achievements.map(({ title, desc }) => (
              <div
                key={title}
                style={{ borderLeftColor: T }}
                className="bg-white border border-gray-200 border-l-4 p-6"
              >
                <h3 className="font-bold text-gray-900 text-sm uppercase tracking-wide mb-2 font-outfit">
                  {title}
                </h3>
                <p className="text-gray-500 text-xs leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S8 — CONTACT
      ══════════════════════════════════════════════ */}
      <section className="py-20 px-4">
        <div className="max-w-5xl mx-auto">
          <SectionLabel>Contact</SectionLabel>
          <SectionHeading>Get in touch</SectionHeading>
          <Divider />

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {contacts.map(({ Icon, label, lines }) => (
              <div key={label} className="bg-gray-50 border border-gray-200 p-6">
                <div
                  style={{ color: T }}
                  className="mb-4"
                >
                  <Icon className="h-6 w-6" />
                </div>
                <p
                  style={{ color: T, letterSpacing: '0.1em' }}
                  className="text-[10px] font-black uppercase mb-2"
                >
                  {label}
                </p>
                {lines.map((line, i) => (
                  <p
                    key={i}
                    className={`text-xs leading-snug ${
                      i === lines.length - 1 ? 'text-gray-400 italic mt-1' : 'text-gray-700 font-medium'
                    }`}
                  >
                    {line}
                  </p>
                ))}
              </div>
            ))}
          </div>

          {/* Footer note */}
          <div className="mt-12 pt-8 border-t border-gray-200">
            <p className="text-[11px] text-gray-400 uppercase tracking-wider font-bold text-center">
              Ganga Guardian AI — A National Mission for Clean Ganga Initiative &nbsp;|&nbsp; Ministry of Jal Shakti, Government of India &nbsp;|&nbsp; © 2026
            </p>
          </div>
        </div>
      </section>

    </div>
  );
}
