import React, { useEffect, useState } from 'react';
import { Loader2, Play } from 'lucide-react';
import { api } from '../utils/api';

export default function DigitalTwin() {
  const [location, setLocation] = useState(''); const [locations, setLocations] = useState([]); const [options, setOptions] = useState({ haltTanneries: false, stpBypass: false, aerators: false }); const [result, setResult] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { api.get('/dashboard/stats').then((data) => { const values = data.locationData || []; setLocations(values); setLocation(values[0]?._id || ''); }).catch((err) => setError(err.message)); }, []);
  const simulate = async () => { setLoading(true); setError(''); try { const response = await api.post('/digital-twin/simulate', { location, ...options }); if (response.availability !== 'available') throw new Error(response.message || 'No baseline observation is available.'); setResult(response.simulation); } catch (err) { setError(err.message); setResult(null); } finally { setLoading(false); } };
  return <div className="mx-auto max-w-5xl px-4 py-12 text-left"><h1 className="font-outfit text-2xl font-black uppercase text-primary">Digital Twin simulator</h1><p className="mt-1 text-xs font-bold uppercase tracking-widest text-gray-500">Modeled outcomes from a real station baseline</p><div className="mt-8 grid gap-6 md:grid-cols-2"><div className="border border-gray-200 bg-white p-6"><label className="text-xs font-bold uppercase text-gray-600">Baseline station<select value={location} onChange={(event) => setLocation(event.target.value)} className="mt-2 w-full border border-gray-300 p-3 text-sm"><option value="">Select station</option>{locations.map((item) => <option key={item._id} value={item._id}>{item._id}</option>)}</select></label><div className="mt-6 space-y-4">{[['haltTanneries', 'Halt upstream industrial discharge'], ['stpBypass', 'Resolve sewage treatment overflow'], ['aerators', 'Deploy emergency aerators']].map(([key, label]) => <label key={key} className="flex gap-3 text-sm"><input type="checkbox" checked={options[key]} onChange={(event) => setOptions({ ...options, [key]: event.target.checked })} />{label}</label>)}</div><button disabled={!location || loading} onClick={simulate} className="mt-8 inline-flex w-full items-center justify-center gap-2 bg-primary py-3 text-xs font-bold uppercase text-white disabled:opacity-50">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />} Run simulation</button></div><div className="border border-gray-200 bg-white p-6">{error && <div role="alert" className="mb-4 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{!result && !error && <p className="text-sm text-gray-500">Select a station and intervention to calculate a scenario.</p>}{result && <><h2 className="font-outfit text-lg font-black uppercase text-primary">Before / after</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{[['BOD', result.beforeValues.bodLevel, result.afterValues.bodLevel], ['Fish-kill risk', result.beforeValues.fishKillRisk, result.afterValues.fishKillRisk], ['Dolphin habitat risk', result.beforeValues.dolphinHabitatRisk, result.afterValues.dolphinHabitatRisk]].map(([label, before, after]) => <div key={label} className="border p-4"><div className="text-xs font-bold uppercase text-gray-500">{label}</div><div className="mt-2 text-sm">{before} → <strong>{after}</strong></div></div>)}</div><p className="mt-5 text-xs text-gray-500">Scenario coefficients are configurable planning estimates, not measured outcomes.</p></>}</div></div></div>;
}
