import React, { useEffect, useState } from 'react';
import { Activity, AlertTriangle, ArrowRight, Map, ShieldCheck } from 'lucide-react';
import { api } from '../utils/api';

export default function Home({ onNavigate }) {
  const [stats, setStats] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => { api.get('/dashboard/stats').then(setStats).catch((err) => setError(err.message)); }, []);
  return <div>
    <section className="bg-primary px-4 py-24 text-center text-white"><div className="mx-auto max-w-5xl"><h1 className="font-outfit text-4xl font-black uppercase md:text-6xl">Ganga Guardian <span className="text-accent">AI</span></h1><p className="mt-4 text-lg text-accent">River intelligence from synchronized observations.</p><div className="mt-10 flex flex-wrap justify-center gap-3"><button onClick={() => onNavigate('/login')} className="inline-flex items-center gap-2 bg-accent px-5 py-3 text-sm font-black uppercase text-primary">Open portal <ArrowRight className="h-4 w-4" /></button><button onClick={() => onNavigate('/about')} className="border border-white/30 px-5 py-3 text-sm font-black uppercase">About platform</button></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-12"><div className="mb-8 flex items-center justify-between"><div><h2 className="font-outfit text-2xl font-black uppercase text-primary">Current system status</h2><p className="text-sm text-gray-500">Values below come from the synchronized backend; unavailable values are not estimated.</p></div><Activity className="h-8 w-8 text-safe-green" /></div>{error && <div role="alert" className="mb-6 border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Backend unavailable: {error}</div>}<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[['Reports', stats?.totalReports], ['Active alerts', stats?.activeAlerts], ['Observations', stats?.totalSensorReadings], ['Monitoring stations', stats?.monitoringLocations]].map(([label, value]) => <div key={label} className="border border-gray-200 bg-white p-6 shadow-sm"><div className="font-outfit text-3xl font-black text-primary">{value ?? '—'}</div><div className="mt-2 text-xs font-bold uppercase tracking-widest text-gray-500">{label}</div></div>)}</div><div className="mt-10 grid gap-6 md:grid-cols-3"><div className="border border-gray-200 p-6"><ShieldCheck className="mb-4 h-8 w-8 text-safe-green" /><h3 className="font-bold text-primary">Evidence-first monitoring</h3><p className="mt-2 text-sm text-gray-600">Each observation retains its provider, source URL, and observation time.</p></div><div className="border border-gray-200 p-6"><Map className="mb-4 h-8 w-8 text-primary" /><h3 className="font-bold text-primary">GIS context</h3><p className="mt-2 text-sm text-gray-600">Stations, river stretches, facilities, and reports are shown only when persisted.</p></div><div className="border border-gray-200 p-6"><AlertTriangle className="mb-4 h-8 w-8 text-alert-red" /><h3 className="font-bold text-primary">Honest alerts</h3><p className="mt-2 text-sm text-gray-600">No-data and stale states are visible instead of being hidden behind demo values.</p></div></div></section>
  </div>;
}
