import React, { useEffect, useState } from 'react';
import { AlertTriangle, Factory, Loader2, ShieldCheck } from 'lucide-react';
import { api } from '../utils/api';

export default function IndustryPortal() {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { api.get('/industry/compliance').then(setData).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="flex justify-center py-24"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>;
  return <div className="mx-auto min-h-[calc(100vh-200px)] max-w-6xl px-4 py-12 text-left"><h1 className="font-outfit text-2xl font-black uppercase text-primary">Industry compliance portal</h1><p className="mt-1 text-xs font-bold uppercase tracking-widest text-gray-500">Persisted compliance and emissions observations</p>{error && <div role="alert" className="mt-6 border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{!error && !data?.industry && <div className="mt-8 border border-amber-200 bg-amber-50 p-6 text-sm text-amber-800">No industry record is linked to this account yet. Ask an administrator to link your facility.</div>}{data?.industry && <><div className="mt-8 grid gap-5 md:grid-cols-3"><div className="border border-gray-200 bg-white p-6"><Factory className="mb-3 h-6 w-6 text-primary" /><div className="font-bold text-primary">{data.industry.name}</div><div className="text-xs text-gray-500">{data.industry.category}</div></div><div className="border border-gray-200 bg-white p-6"><ShieldCheck className="mb-3 h-6 w-6 text-safe-green" /><div className="font-bold text-primary">{data.alerts?.length ? 'Review required' : 'No recorded exceedance'}</div><div className="text-xs text-gray-500">Based on persisted compliance readings</div></div><div className="border border-gray-200 bg-white p-6"><AlertTriangle className="mb-3 h-6 w-6 text-gray-400" /><div className="font-bold text-primary">{data.records?.length ?? 0}</div><div className="text-xs text-gray-500">Compliance observations</div></div></div><div className="mt-8 overflow-x-auto border border-gray-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="p-4">Pollutant</th><th className="p-4">Observed</th><th className="p-4">Limit</th><th className="p-4">Observed at</th></tr></thead><tbody>{data.records?.map((record) => <tr key={record._id} className="border-t"><td className="p-4">{record.pollutant}</td><td className="p-4">{record.value} {record.unit}</td><td className="p-4">{record.limit} {record.unit}</td><td className="p-4">{new Date(record.observedAt).toLocaleString()}</td></tr>)}</tbody></table>{!data.records?.length && <p className="p-8 text-center text-sm text-gray-500">No compliance records available.</p>}</div></>}</div>;
}
