import React, { useEffect, useState } from 'react';
import { Loader2, RefreshCw } from 'lucide-react';
import { api } from '../utils/api';

export default function RiverStatus() {
  const [stations, setStations] = useState([]); const [selected, setSelected] = useState(''); const [health, setHealth] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const overview = await api.get('/dashboard/stats'); setStations(overview.locationData || []); setSelected((current) => current || overview.locationData?.[0]?._id || ''); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { if (selected) api.get(`/dashboard/river-health/${encodeURIComponent(selected)}`).then(setHealth).catch(() => setHealth(null)); }, [selected]);
  const reading = health?.latestReading;
  return <div className="mx-auto max-w-6xl px-4 py-12 text-left"><div className="mb-8 flex items-center justify-between"><div><h1 className="font-outfit text-2xl font-black uppercase text-primary">River status</h1><p className="text-xs font-bold uppercase tracking-widest text-gray-500">Station health from synchronized observations</p></div><button onClick={load} className="inline-flex items-center gap-2 border border-gray-300 px-3 py-2 text-xs font-bold uppercase"><RefreshCw className="h-4 w-4" /> Refresh</button></div>{error && <div className="mb-6 border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}<select value={selected} onChange={(event) => setSelected(event.target.value)} className="mb-8 w-full max-w-md border border-gray-300 p-3 text-sm"><option value="">Select a synchronized station</option>{stations.map((station) => <option key={station._id} value={station._id}>{station._id}</option>)}</select>{loading ? <div className="flex justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div> : !health || health.availability !== 'available' ? <div className="border border-amber-200 bg-amber-50 p-6 text-sm text-amber-800">No observation is available for this station.</div> : <><div className="grid gap-6 md:grid-cols-3"><div className="border border-gray-200 bg-white p-6 text-center"><div className="font-outfit text-6xl font-black text-primary">{health.healthScore}</div><div className="mt-2 text-xs font-bold uppercase tracking-widest">{health.status}</div></div><div className="border border-gray-200 bg-white p-6"><div className="text-xs font-bold uppercase text-gray-500">Source</div><div className="mt-2 text-sm font-semibold">{health.source}</div><div className="mt-4 text-xs text-gray-500">Observed {new Date(health.observedAt).toLocaleString()}</div></div><div className="border border-gray-200 bg-white p-6"><div className="text-xs font-bold uppercase text-gray-500">Station</div><div className="mt-2 text-sm font-semibold">{health.location}</div></div></div><div className="mt-8 overflow-x-auto border border-gray-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="p-4">Parameter</th><th className="p-4">Observed value</th></tr></thead><tbody>{[['pH', reading.pH], ['Dissolved oxygen', reading.DO], ['BOD', reading.BOD], ['Turbidity', reading.turbidity], ['Fecal coliform', reading.fecalColiform], ['Heavy metals', reading.heavyMetals]].map(([label, value]) => <tr key={label} className="border-t"><td className="p-4 font-semibold">{label}</td><td className="p-4">{value ?? 'Not measured'}</td></tr>)}</tbody></table></div></>}</div>;
}
